version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn daliBenJemaaDotCom.wsgi:application --bind 0.0.0.0:8000 --timeout 300"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles  # Mount the static volume
    ports:
      - "8000:8000"
    env_file:
      - secret.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:16 #Use a specific version for stability.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - secret.env
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles  # Mount the static volume for nginx
    ports:
      - "80:80"
      - "443:443" # Add this line for HTTPS
    depends_on:
      - web
    restart: always
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:ro
    environment:
      - SEARXNG_HOSTNAME=localhost
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  postgres_data:
  static_volume:  # Define the static volume
  searxng_data:  # Define the searxng volume
