# Generated by Django 5.1.6 on 2025-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
