use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG for RAG System"

search:
  safe_search: 0
  formats:
    - html
    - json
  max_page: 20

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "your-secret-key-change-this"
  base_url: false

ui:
  default_theme: "simple"

outgoing:
  request_timeout: 2.0
  max_request_timeout: 3.0
  useragent_suffix: "SearXNG"
  pool_connections: 100
  pool_maxsize: 100
  enable_http2: true
  max_connections: 20
  max_keepalive_connections: 2
  keepalive_expiry: 0
  max_redirects: 5
  retries: 3
  retry_on_http_error:
    - 408
    - 429
    - 500
    - 502
    - 503
    - 504

engines:
  - name: google
    engine: google
    shortcut: go
    categories: general
    disabled: false
    timeout: 3.0
    tokens: []
    max_page: 20
    safesearch: false
    send_accept_language_header: true

  - name: bing
    engine: bing
    shortcut: bi
    categories: general
    disabled: false
    timeout: 3.0
    tokens: []
    max_page: 20
    safesearch: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: general
    disabled: false
    timeout: 3.0
    tokens: []
    max_page: 20
    safesearch: false

  - name: startpage
    engine: startpage
    shortcut: sp
    categories: general
    disabled: false
    timeout: 3.0
    tokens: []
    max_page: 20
    safesearch: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    categories: general
    disabled: false
    timeout: 3.0
    tokens: []
    max_page: 20
    safesearch: false